version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Building Docker image
      - docker build -t nginx:latest .
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 918462768359.dkr.ecr.ap-south-1.amazonaws.com
      - docker tag nginx:latest 918462768359.dkr.ecr.ap-south-1.amazonaws.com/nginx:latest
      - docker push 918462768359.dkr.ecr.ap-south-1.amazonaws.com/nginx:latest
      - echo Build completed on `date`

  post_build:
    commands:
      - echo Generating imagedefinitions.json
      - printf '[{"name":"nginx1latest","imageUri":"918462768359.dkr.ecr.ap-south-1.amazonaws.com/nginx1latest:latest"}]' > imagedefinitions.json
      - echo Uploading imagedefinitions.json to S3 bucket
      - aws s3 cp imagedefinitions.json s3://artifactscicd1/NEWCICD-2/BuildArtif/imagedefinitions.json

artifacts:
  files:
     - '**/*'
  base-directory: .
  name: newcicd2-backend-build-artifact
  discard-paths: no

