version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Building Docker image
      - docker build -t nginx1latest:latest .
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 918462768359.dkr.ecr.ap-south-1.amazonaws.com
      - docker tag nginx1latest:latest 918462768359.dkr.ecr.ap-south-1.amazonaws.com/nginx1latest:latest
      - docker push 918462768359.dkr.ecr.ap-south-1.amazonaws.com/nginx1latest:latest
      - echo Build completed on `date`

  post_build:
    commands:
      - echo Uploading artifacts to S3 bucket
      - aws s3 cp . s3://artifactscicd1/ --recursive

artifacts:
  files:
    - '**/*'
  base-directory: base_location
  name: newcicd2-backend-build-artifact
  discard-paths: no

